#!/usr/bin/env bash
# Task 01
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo rm -rf /var/www/html/*
echo "Holberton School" | sudo tee -a /var/www/html/page.html > /dev/null
sudo rm -rf /etc/nginx/sites-available/default
printf "server {\n\tlisten 80;\n\tlisten [::]:80;\n\tserver_name Holbi.com;\n\troot /var/www/html;\n\tindex page.html;\n\tlocation / {\n\t\t try_files \$uri \$uri/ =404;\n\t}\n}" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
sudo systemctl restart nginx
