#!/usr/bin/env bash
# Task 0
printf "server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server ipv6only=on;\n\tserver_name localhost;\n\troot /usr/share/nginx/html;\n\tindex index.html index.htm;\n\tlocation / {\n\t\t try_files \$uri \$uri/ =404;\n\t}\n}" | sudo tee /etc/nginx/sites-enabled/default > /dev/null
sudo service nginx restart