#!/usr/bin/env bash
# Advance #1
file="/etc/passwd"
while IFS=: read -r c1 c2 c3 c4 c5 c6 c7; do
printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$c1" "$c4" "$c6" "$c7" "$c3" "$c2" "$c5"
done <"$file"
