#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
hour=0
min=1
while [ $hour -le "12" ]; do
	min=1
	echo "Hour: $hour"
	while [ $min -le "59" ]; do
	echo "$min"
	((min++))
	done
	((hour++))
done
